name: CorePlugin
main: net.guardcode.Core
author: szymeko
version: 0.1
commands:
  msg:
    aliases:
      - "message"
      - "r"
  night:
    aliases:
      - "noc"
  day:
    aliases:
      - "dzien"